# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Dropfort Vagrantfile
# This file was generated by Dropfort.com
#
# Dropfort machine: https://app.dropfort.com/machine/2294
# Dropfort environent: https://app.dropfort.com/environment/694

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.8.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.host_name = 'fcc98784-cded-4012-88c0-5fed1eda2f05.dropfort.com'
  config.vm.box = "centos/7"

  config.vm.box_version = ">= 0"

  config.puppet_install.puppet_version = "3.8.7"

  config.vm.network :forwarded_port, guest: 80, host: 8080, protocol: "tcp", auto_correct: true	# Apache HTTP
  config.vm.network :forwarded_port, guest: 443, host: 8443, protocol: "tcp", auto_correct: true	# Apache HTTPS
  config.vm.network :forwarded_port, guest: 3306, host: 3306, protocol: "tcp", auto_correct: true	# MySQL


  config.ssh.forward_agent = true
  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]

    # Customize the DNS settings to speed up network requests
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.post_up_message = "Provisioned by Dropfort.com"

  config.vm.provision :shell, inline: "if [ ! $(grep single-request-reopen /etc/sysconfig/network) ]; then echo RES_OPTIONS=single-request-reopen >> /etc/sysconfig/network && service network restart; fi"

  # Set puppet keys
  config.vm.provision :shell, inline: "mkdir -p /var/lib/puppet/ssl/private_keys && echo '-----BEGIN PRIVATE KEY-----
MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCZpAosubi52/UO
IupbUkxfsMuedrdEuTqtlbUL/TDuqW3o0jGR0t/FsFkieS1uFnWEHtEzrzEuWFO4
Z0PuSCs1I6I2K2460LlQsN8oEoM5tFiWA+BkXj6V1cfAFGhmQVMjfrzuBntdfzFo
Y/FrYe4jNmsEmtiXE2Q4ys47Nnk9xxg6Gk9tGACLwlwZOlZfs4hRfBxN226RAoMK
85vJo2AfUwk3fZKTWGZEUlfb1jD1QZgB002DhLkjqnEnSoMOomXtJJDWxqfM15TU
POiZYBaKaG5uW/Scchlh99Ofj6mgD7QVIKJNXWq5xqgoT0oiBuNH1gSyHkp4Q7c8
VPhQunFBgyHxA17y27Jx8qCfoRMPhoYSqDy1SYw0PMTQN4Cz5R2jWjb28ZhLKUPs
xKdn66T6KVfF2Evtoo1SOGPMrBXZmPyWS8GFrcN4FLwG/wwH5EBkXo98sMXpyr42
QhvzYK/m0imuhVqvumlYH2QFRuWxxztN3bSXgY7XwLCqHulRnt0FXBbmjLNAaRO+
UeYdmuR2RNU/Rx1VVeDEksVdAGxpF85czxNorhcci0c2pqJy26LfEX8OstrTJV/2
0MR7FqgV6eYp5oBr3mLflJJif9cZC6xg/DAA9og0C66vPiKnxP6iUKM9dtAL6bKU
CI8OEaAw5ZSpVR07tJ5nnHrhYcmh4wIDAQABAoICABC6Ej2CTsE1WD2cwYUFtbjp
R5HN/O/ndqL1XIucmhoxqfyh/bGRkrk0FNAy/yYwHcUvkbkdxq30AdFetL+ZbdLQ
OVXKbqrKlJJbX0A+m7jJkKdsbp6ewBOR/bhEwIT5cbK4lpsXa5DnSxrBXsRBGisN
PqN2tEPmYY/pTICX0qVOKq4QtTr8VPriQyKf/k1W/21XpME5NZVl/5xOn1RZjBp8
8NDww+d0xVWE3XnanOPmq0Tvm03JQlrGsKEFdLVAKvahd39ai2Q6yEI/C1e/ZVTW
P8eWDVCG/4px78E8Y8xASWvPbLwdgoQNQ7t3vmtr8oycmVBHCfaD8MwJuCsZ0UCU
ceZ0ZwRDdbF4GWEDUISl2An8BB+frZgm5QJJlCdCrhAoIcAneKasaYOfsqRW1m8U
De/JB1nYqXFntyTjgDaywcSoNx60qgDOyIzeQgphznMoRGn+cNKkVrDhPxpui4LF
YVr+qbdnJ59+NiDQfDiY2mffL5xRbLiF2NQePgQ+yGApx6c2uxbEHQ6CiJh4+WMr
vS18b+HG38uPi9vDa77BIwa1uG3VWfbjIgjVikc542xDKH6Jnm5DOIIrLqzoFoMu
jdTmUN96o4ifNTv9ZQGy8Tn3m0hVGk/F0tnd4UdNx4I5BjMwZ6KHz3rgH3bLYzz4
pBtSVGNmaA84XaTMRh0RAoIBAQDL+er9q7JDfR8ThbHj9SEZo1slkpS41Df9WS0D
A84FnzeiS40ZQus9+gjJA3677/1s1r0tRRc3o0CD7jJvAZEdtNySxiOVCsOgyjyC
Z+1PrbCjMNuJWAJXJI7UqWQrdL1z+OXlb2fM/MnISzEJbNYJui2DcjFwooSBHjyr
SCJH63V5UcH/TkegdcafQKY8p2v6p5ujpeJZbGcKPTWkhm2T2XUiF9sNJN/pQdWV
BP5L6RqPXC2KqsmeiBWTkVDpJBbMDoX8Q/25s8U8f6Yqoy+ShkrdG9cN5dfnCgqR
xz8+Xf7FFxxIDrWQXDE/+chNUQQmDi4Lh3KSDJcdLrbFXVhZAoIBAQDA05pNHos+
HdNBdM1+fPo3eOoZNf+QNWPiz03c0YsanJC9Mnr8y0T4qjnDXyocaXbH4JYtjSOO
2uz1atpVAdV9KkDqwTm0O8qiUuSvjqkrvUGlNiXpy4K7a0EHn0baBw2jExkQ15St
oSHPjtXwuYKc7P1rrfJ/QEj3Z+AxEYGL84BhXAQjrsIPaeJUEHVpAd6n4gh5QlcC
SEoumlVh3zsZHY/aFADPRh1OfxVg3mfReCyudMRzCInFv4oigtmQq+KErCNagtVH
RXbi7o/kN+1ZnQe0L1OfasBQUmsrCtEBO/8ysdTPNuqooXT9GTRMga4iQ0fbRCI7
KppEo7TbicSbAoIBAAIHfnr/lkptmD2NevOVoLqskV+SUcB0/AmdNYFuLEKKDvei
YMj7jXOUZTn6uuwLuy22BTPKGC0Jhr7JQ98u2M6+2eLr7bax4LhcyrVRa177j2JQ
Ph7jrUJIrtMWzFRSWQAqXb8mmJXFfgxsExTQ7GA0ZfeEz1EbjM3sCxZ5JT4p7YVD
dvafRL8n7M3wyraXw88+k6HRKKtTFMNZUItOexCZfTzVl+xNjZy4dvOAlTcUHpuG
gz157X+SQwSw0WlAXqmxC0wzMPcD/tZXPsP106dVhrEkccNFohw+UVSZ8tsf/ETh
sfpViyDgiezlA0UhpTTrtzGOK2mgjnBP4qmcACECggEBALcI5UHpCWF4LCzI87rq
ZRU86HHv6Nv5YgxMnWtLWJB1J4sAHPBS/vBPnS8P6Ug47/BBBizM+YDD3QQEXqUs
bXs3HZH4wo6L5wf4SW0/rOOA7YwmfwyTClBfOcZDcZzJ7y7plPSAvnemKRL9UaUE
YrAU4WVSI4qY+eompw/MvzyacjV4g9FfNIQvDRCg4uI/TRvtGgAIcdEPz6K3Cu8x
V8a6Ye8u56nYsz7ssN1XoBKc0UT0P/m1lBmqfDPQIzcJgaZQQ+rJoCvcC0LUErAe
SmWzAjoOZoE/creL1IBx7v0N92smlIvxZAOX5xXM0/D/c8zAMrg2z4t8IB2hi66M
8psCggEAdkeu/ZHh1uafLCORcxTPU9Yhej6NBIBwx0Uof3+dlDjXotRAIQx3JNJd
dFrBNdArX6vETjp48xcietFDPIRI6x7Azv6YqzCsfHYvSWEINlppa2rMv9kfS+wM
I2JVykFY4kx8LpIXUxdprepYs09G/j42WLiQnNU7kRdJPeW6276L9V7wCZtJyejV
wthL2ncg3E15qJdgUUN1PPGjVnBAg2MWaZFndNEvzytPxNNme4gE+ri8QdPf3Fwt
m0F70RKnB/UMmjfmo8s0UyXNPgjNa0JJp52LZQ3F4+8LBcRao99xMXMi6qj/khVg
RVz3vNWjVKTKnnbiLTTpA1oXJtdMug==
-----END PRIVATE KEY-----
' > /var/lib/puppet/ssl/private_keys/fcc98784-cded-4012-88c0-5fed1eda2f05.dropfort.com.pem
mkdir -p /var/lib/puppet/ssl/public_keys && echo '-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmaQKLLm4udv1DiLqW1JM
X7DLnna3RLk6rZW1C/0w7qlt6NIxkdLfxbBZInktbhZ1hB7RM68xLlhTuGdD7kgr
NSOiNituOtC5ULDfKBKDObRYlgPgZF4+ldXHwBRoZkFTI3687gZ7XX8xaGPxa2Hu
IzZrBJrYlxNkOMrOOzZ5PccYOhpPbRgAi8JcGTpWX7OIUXwcTdtukQKDCvObyaNg
H1MJN32Sk1hmRFJX29Yw9UGYAdNNg4S5I6pxJ0qDDqJl7SSQ1sanzNeU1DzomWAW
imhublv0nHIZYffTn4+poA+0FSCiTV1qucaoKE9KIgbjR9YEsh5KeEO3PFT4ULpx
QYMh8QNe8tuycfKgn6ETD4aGEqg8tUmMNDzE0DeAs+Udo1o29vGYSylD7MSnZ+uk
+ilXxdhL7aKNUjhjzKwV2Zj8lkvBha3DeBS8Bv8MB+RAZF6PfLDF6cq+NkIb82Cv
5tIproVar7ppWB9kBUblscc7Td20l4GO18Cwqh7pUZ7dBVwW5oyzQGkTvlHmHZrk
dkTVP0cdVVXgxJLFXQBsaRfOXM8TaK4XHItHNqaictui3xF/DrLa0yVf9tDEexao
FenmKeaAa95i35SSYn/XGQusYPwwAPaINAuurz4ip8T+olCjPXbQC+mylAiPDhGg
MOWUqVUdO7SeZ5x64WHJoeMCAwEAAQ==
-----END PUBLIC KEY-----
' > /var/lib/puppet/ssl/public_keys/fcc98784-cded-4012-88c0-5fed1eda2f05.dropfort.com.pem
"
  # Set puppet master
  config.vm.provision "puppet_server" do |puppet|
    puppet.puppet_server = "provisioner.dropfort.com"
    puppet.puppet_node = "fcc98784-cded-4012-88c0-5fed1eda2f05.dropfort.com"
    puppet.options = "--verbose --waitforcert=15 --pluginsync --configtimeout=10m --environment dropfort"
    puppet.facter = {
      "dropfort_vagrant" => true
    }
  end
end
